assert(SMODS.load_file('src/util.lua'))()
assert(SMODS.load_file('src/joker.lua'))()
assert(SMODS.load_file('src/back.lua'))()
assert(SMODS.load_file('src/tag.lua'))()
assert(SMODS.load_file('src/blind.lua'))()
